
package eberthClient.generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISimpleInterface", targetNamespace = "http://eberth/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISimpleInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns eberthClient.generate.DummyData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://eberth/", className = "eberthClient.generate.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://eberth/", className = "eberthClient.generate.GetDataResponse")
    @Action(input = "http://eberth/ISimpleInterface/getDataRequest", output = "http://eberth/ISimpleInterface/getDataResponse")
    public DummyData getData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saySomething", targetNamespace = "http://eberth/", className = "eberthClient.generate.SaySomething")
    @ResponseWrapper(localName = "saySomethingResponse", targetNamespace = "http://eberth/", className = "eberthClient.generate.SaySomethingResponse")
    @Action(input = "http://eberth/ISimpleInterface/saySomethingRequest", output = "http://eberth/ISimpleInterface/saySomethingResponse")
    public String saySomething();

}
